baseURL = "https://hjertnes.blog/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hjertnes.blog"
theme = "hjertnes"
rssLimit = 25
paginate = 10
copyright = ""

[author]
  name = "Eivind Hjertnes"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]] 
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]] 
  name = "About"
  weight = 20
  identifier = "about"
  url = "/about"
[[menu.main]] 
  name = "Colophon"
  weight = 20
  identifier = "colophon"
  url = "/colophon"
[[menu.main]] 
  name = "Contact"
  weight = 20
  identifier = "contact"
  url = "/contact"
[[menu.main]] 
  name = "Now"
  weight = 20
  identifier = "now"
  url = "/now"
[[menu.main]] 
  name = "Uses"
  weight = 20
  identifier = "uses"
  url = "/uses"
[[menu.main]]
  name = "Archives"
  weight = 30
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Feed"
  weight = 40
  identifier = "feed"
  url = "/index.xml"

[params]
  logoTitle = "Hjertnes.blog"
  description = "Eivind Hjertnes's blog."
  archivePaginate = 9999 
  dateFormatToUse = "2006-01-02"
